name: Run Selectors Tests & Report

# trigger manually or on push to main (adjust as needed)
on:
  workflow_dispatch:
    inputs:
      generate_lock_forced:
        description: 'If true, create a new package-lock.json, even if it already exists'
        required: false
        default: 'true'
  
permissions:
  contents: write   # allow committing log files
  issues: write     # allow creating/updating issues

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for running tests)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-deps # Assign an ID for later reference
        uses: actions/cache@v4 # Use the latest version of the cache action
        with:
          path: |
            ~/node_modules
            ~/chrome
            /snap
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Unique key based on OS and package-lock.json hash
          restore-keys: |
            ${{ runner.os }}-node-
    
      - name: Ensure package-lock.json (generate and commit if missing)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          if [ "${{ github.event.inputs.generate_lock_forced }}" = "true" ]; then
            echo "Generating package-lock.json"
            npm install --package-lock-only
            echo "lock_exists=true" >> $GITHUB_OUTPUT
          else
            if [ -f package-lock.json ]; then
              echo "lock_exists=true" >> $GITHUB_OUTPUT
            else
              echo "Generating package-lock.json (package-lock-only)"
              npm install --package-lock-only
              echo "lock_exists=true" >> $GITHUB_OUTPUT
            fi
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # add files
          git add package-lock.json

          git commit -m "ci(deps): added/updated package-lock.json" || echo "No changes to commit"

          # push to main
          git push origin HEAD:main || echo "Push failed (branch protection?)"

      - name: Install dependecies (if cache miss)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          echo
          echo "Installing node dependencies..."
          echo
          npm ci
          echo
          echo
          # try npx installer
          echo "Installing puppeteer browsers (prefer npx)"
          if npx --yes @puppeteer/browsers install chrome@121.0.6167.85; then
            echo "npx browser installer succeeded"
          else
            echo "npx browser installer failed; attempting to install puppeteer and let it fetch the browser"
            npm explore puppeteer -- npm run install || true
          fi

          # locate a likely chrome binary from installed puppeteer local-chromium
          # typical path: node_modules/puppeteer/.local-chromium/linux-*/chrome-linux64/chrome
          CHROME_SRC=$(find node_modules -type f -path "*/.local-chromium/*/chrome-linux64/chrome" -print -quit || true)
          echo "Found chrome candidate at: $CHROME_SRC"

          if [ -z "$CHROME_SRC" ]; then
            echo "No chrome binary found under node_modules/.local-chromium. Attempting fallback: apt-get chromium-browser"
            sudo apt-get update
            sudo apt-get install -y chromium-browser || true
            if command -v chromium-browser >/dev/null 2>&1; then
              CHROME_SRC=$(command -v chromium-browser)
              echo "Found system chromium at $CHROME_SRC"
            fi
          fi

          if [ -z "$CHROME_SRC" ]; then
            echo "Could not find a chrome binary to commit. Exiting with non-zero (you can still commit manually)."
            exit 1
          fi

          DEST_DIR="chrome/linux-121.0.6167.85/chrome-linux64"
          mkdir -p "$DEST_DIR"
          cp -v "$CHROME_SRC" "$DEST_DIR/chrome"
          chmod +x "$DEST_DIR/chrome"
          echo "Copied chrome to $DEST_DIR/chr
          ome"

          echo
          echo
          echo "Installing chromium snap..."
          echo
          echo "Attempting install..."
          sudo snap install chromium

      - name: Prepare logs dir
        run: |
          mkdir -p logs

      - name: Run selector tests (node)
        id: run_tests
        # capture both stdout and stderr to file
        run: |
          TIMESTAMP=$(date --utc +"%Y-%m-%dT%H%M%SZ")
          # run test runner; save combined stdout+stderr
          node ./node/test/test-runner.js 2>&1 | tee logs/test-run-${TIMESTAMP}.log
          echo "logfile=logs/test-run-${TIMESTAMP}.log" >> $GITHUB_OUTPUT

      - name: Commit log file (if changed)
        if: always()
        run: |
          logpath=$(jq -r '.logfile' <<< "${{ steps.run_tests.outputs }}" 2>/dev/null || echo "${{ steps.run_tests.outputs.logfile }}")
          # fallback if above doesn't work:
          logpath=${logpath:-logs/test-run-$(date --utc +"%Y-%m-%dT%H%M%SZ").log}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$logpath" || true
          # only commit if staged changes
          if ! git diff --cached --quiet; then
            git commit -m "chore(tests): add test log $logpath" || true
            git push origin HEAD:main || true
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
