name: Scraper - Test

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to test (inquirer or philstar)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  ensure-lockfile:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.check_lock.outputs.created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for package-lock.json
        id: check_lock
        run: |
          if [ -f package-lock.json ]; then
            echo "created=false" >> $GITHUB_OUTPUT
          else
            echo "created=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate package-lock.json and commit node_modules (if missing)
        if: steps.check_lock.outputs.created == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --no-audit --no-fund
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json node_modules || true
          git commit -m "chore(ci): add package-lock.json and node_modules [skip ci]" || echo "No changes to commit"
          BRANCH="${{ github.ref_name }}"
          if [ -z "$BRANCH" ]; then
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi
          git push origin HEAD:"$BRANCH" || echo "Push failed (branch protection?)"

  install-deps:
    needs: ensure-lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Use committed node_modules if present, otherwise install and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          if [ -d "node_modules" ]; then
            echo "node_modules already present from repo — skipping install"
            ls -ld node_modules || true
            exit 0
          fi

          echo "node_modules not present; running npm ci to install deps"
          npm ci

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add node_modules || true
          git commit -m "chore(ci): add node_modules [skip ci]" || echo "No changes to commit"
          BRANCH="${{ github.ref_name }}"
          if [ -z "$BRANCH" ]; then
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi
          git push origin HEAD:"$BRANCH" || echo "Push failed (branch protection?)"

  run-tests:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure node_modules
        run: |
          if [ -d "node_modules" ]; then
            echo "node_modules present — ready to run tests"
          else
            echo "node_modules missing — running npm ci as fallback"
            npm ci
          fi
      - name: Ensure Chromium (try npx then apt fallback)
        run: |
          set -e
          PKG_VER=$(node -e "try{console.log(require('puppeteer/package.json').version)}catch(e){console.log('latest')}")
          echo "puppeteer version: $PKG_VER"
          # try npx installer first; if it fails, fall back to apt
          if npx --yes puppeteer@$PKG_VER browsers install chrome; then
            echo "npx puppeteer browser install succeeded"
          else
            echo "npx install failed — falling back to apt"
            sudo apt-get update
            sudo apt-get install -y chromium-browser
          fi
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.site }}" = "" ]; then
            npm test
          else
            npm test -- --site="${{ github.event.inputs.site }}"
          fi

      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results